name: Run Unit Tests
on:
    pull_request:
    push:
        branches:
            - master

jobs:
    run_jest_tests:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Run Tests
              run: |
                  npm ci
                  npm run test

